### ISSUE TITLE
Verify CSV status 

### ISSUE THREAD

**Issue by luiscachog** [open-cluster-management-io/policy-generator-plugin#125]
Hello!

While creating a policy using the web ui in RHACM, I have the option to add a `CSV status` policy where the policy is in charge to monitor that the Operator CSV is in `Succeeded` status, the autogenerated yaml file looks like:

```yaml
    - complianceType: musthave
        objectDefinition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: ClusterServiceVersion
          metadata:
            namespace: openshift-compliance
          spec:
            displayName: Compliance Operator
          status:
            phase: Succeeded
            reason: InstallSucceeded
```

I'm trying to use this plugin to simulate that behavior by defining the next:

```shell
compliance-operator
├── kustomization.yml
├── operator
│   ├── base
│   │   ├── csv-status.yaml
│   │   ├── kustomization.yaml
│   │   ├── namespace.yaml
│   │   ├── operator-group.yaml
│   │   └── subscription.yaml
│   └── overlays
│       └── default
│           ├── kustomization.yaml
│           └── patch-channel.yaml
└── policyGenerator.yaml
```

The content of `compliance-operator/kustomization.yml` is:

```yaml
generators:
- ./policyGenerator.yaml
commonLabels:
  open-cluster-management.io/policy-set: install-operators
commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
```

Then, `compliance-operator/policyGenerator.yaml`

```yaml
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-install-compliance-operator
placementBindingDefaults:
  name: binding-policy-install-compliance-operator
policyDefaults:
  namespace: my-policies
  categories:
    - CM Configuration Management
    - CA Security Assessment and Authorization
  controls:
    - CM-2 Baseline Configuration
    - CA-2 Security Assessments
    - CA-7 Continuous Monitoring
  standards:
    - NIST SP 800-53
  policyAnnotations:
    policy.open-cluster-management.io/description: "Installs Compliance Operator"
  placement:
    clusterSelectors:
      matchExpressions:
        - key: environment
          operator: In
          values:
            - production
            - dev
            - qa
        - key: vendor
          operator: In
          values:
            - OpenShift
  policySets:
    - install-operators
  remediationAction: enforce
  severity: high

policies:
- name: policy-install-compliance-operator
  disabled: false
  manifests:
    - path: operator/overlays/default
policySets:
- name: install-operators
  description: Install all the required Operators
```

Then, `compliance-operator/operator/overlays/default/kustomization.yaml`

```yaml
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: compliance-operator
    path: patch-channel.yaml
```

We apply the patch, correctly

So, `compliance-operator/operator/overlays/default/patch-channel.yaml` content is:

```yaml
- op: replace
  path: /spec/channel
  value: stable
```

Then, `compliance-operator/operator/base/kustomization.yaml` content is:

```yaml
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - namespace.yaml
  - operator-group.yaml
  - subscription.yaml
  - csv-status.yaml
 ```

And the `csv-status.yaml` content is:

```yaml
---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  namespace: openshift-compliance
spec:
  displayName: Compliance Operator
  status:
    phase: Succeeded
    reason: InstallSucceeded
```

Note, that I'm not specifying any `metadata.name` as that is how the RHACM web ui autogenerate it and that is the way to verify the status because the name is also autogenerated.

So, when I put all together, and run the `kustomize build` command, I get this error:

```shell
kustomize build --enable-alpha-plugins > compliance-operator-policy.yaml
error generating policies from the PolicyGenerator file '/var/folders/l0/vvhr89r17f170c_737kjmny40000z8/T/kust-plugin-config-246562119': failed to process provided kustomize directory 'operator/overlays/default': accumulating resources: accumulation err='accumulating resources from '../../base': 'PATH/components/policygenerator/apps/compliance-operator/operator/base' must resolve to a file': recursed accumulation of path 'PATH/components/policygenerator/apps/compliance-operator/operator/base': accumulating resources: accumulation err='accumulating resources from 'csv-status.yaml': missing metadata.name in object {{operators.coreos.com/v1alpha1 ClusterServiceVersion} {{ openshift-compliance} map[] map[]}}': must build at directory: 'PATH/components/policygenerator/apps/compliance-operator/operator/base/csv-status.yaml': file is not directory
Error: failure in plugin configured via /var/folders/l0/vvhr89r17f170c_737kjmny40000z8/T/kust-plugin-config-246562119; exit status 1: exit status 1
```

As you can see, the error is that I haven't defined a `metadata.name` object, but I don't need it/want it.

What options do I have to get a similar behavior as I got from the RHACM web ui?

Thank you

**Comment by dhaiducek** [comment]
Hi @luiscachog! This is definitely a limitation of passing the manifest through Kustomize that it validates the YAML as a valid Kubernetes object. Currently the way around this that I can think of offhand (which, I'll admit, isn't all that elegant) is to leave the name in the YAML for Kustomize and then use a patch in the `kustomization.yaml` to remove the name from the result, something like this (you might need to adjust the indices depending on how the array is ordered):

```yaml
patches:
- target:
    group: policy.open-cluster-management.io
    version: v1
    kind: Policy
    name: policy-install-compliance-operator
  patch: |-
    - op: remove
      path: /spec/policy-templates/0/objectDefinition/spec/object-templates/3/objectDefinition/metadata/name
```
